### ISSUE TITLE
Unikraft Redis stops processing requests (crashes) on increased load.

### ISSUE THREAD

**Issue by andrejvelichkovski** [unikraft/lib-redis#9]
Hello,

I was recently trying Redis on the new Unikraft version, and I noticed that it crashes (stops processing) requests when run under an increased workload. This happens when running a `redis-benchmark` with more requests. After it crashes, it doesn't respond to either `ping` or `redis-cli`. I noticed [similar behaviour with Nginx on the new UK version](https://github.com/unikraft/app-nginx/issues/9).

To reproduce, I started the Redis instance with the [unikraft-upb/scripts](https://github.com/unikraft-upb/scripts) for redis. I then run a simple `redis-benchmark` with 10 million GET and SET requests.

**Comment by eduardvintila** [comment]
Fixed by https://github.com/unikraft/unikraft/commit/83da8ab855d6a67db09b135893f16976aa4ea16b
